#pylint: skip-file
from main.models import db, User, Sign, Category, Learn, Bookmark

Learn.query.delete()
Bookmark.query.delete()
Sign.query.delete()
Category.query.delete()
db.session.commit()

num_cat = Category(name='Numbers')
abc_cat = Category(name='Alphabets')
db.session.add(num_cat)
db.session.add(abc_cat)
db.session.commit()

db.session.add(Sign(name='A', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='B', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='C', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='D', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='E', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='F', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='G', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='H', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='I', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='J', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='K', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='L', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='M', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='N', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='O', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='P', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='Q', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='R', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='S', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='T', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='U', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='V', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='W', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='X', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='Y', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='Z', cat_id=abc_cat.cat_id))
db.session.add(Sign(name='Zero', cat_id=num_cat.cat_id))
db.session.add(Sign(name='One', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Two', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Three', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Four', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Five', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Six', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Seven', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Eight', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Nine', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Ten', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Eleven', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Twelve', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Thirteen', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Fourteen', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Fifteen', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Sixteen', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Seventeen', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Eighteen', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Nineteen', cat_id=num_cat.cat_id))
db.session.add(Sign(name='Twenty', cat_id=num_cat.cat_id))
db.session.commit()
