version: "3.7"
services:
    openpose-server:
        build: ./openpose-server
        ports:
            - 80:80
        depends_on:
            - db-server
    db-server:
        build: ./db-server
        ports:
            - 5000:5000
