version: "3.7"
services:
    openpose-server:
        build: ./openpose-server
        ports:
            - 5001:5001
        depends_on:
            - db-server
    db-server:
        build: ./db-server
        ports:
            - 5000:5000
        volumes: 
            - "./db/site.db:/usr/src/app/main/site.db"
